import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/components/Providers";
import Footer from "../components/Footer";
import BlogHeader from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blogs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className + " flex flex-col min-h-screen bg-cyan-300"}
      >
        <Providers>
          <BlogHeader />
          <div className="felx-1">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
